### ISSUE TITLE
Baseline alignment

### ISSUE THREAD

**Issue by gchegr** [isaaclyman/novel-word-count-obsidian#24] opened 2022-12-21 07:33 UTC
**Problem**

I failed to make a CSS snippet to align the numbers to their respective baselines . Whenever the font-size is smaller than 1em, the element jumps up. I assume it gets laid out from the top left corner, and I am not able to restyle it on my own.

**Idea**

Allow to change the alignment of numbers from the current 'top' to 'baseline'.
So far I had to workaround it with lowering opacity and right alignment.

**Comment by isaaclyman** [comment] 2022-12-21 16:13
I'll look into it.

**Comment by isaaclyman** [comment] 2022-12-24 16:56
@gchegr I've been tweaking a bunch of styles and I'm not able to see the issue you're talking about. Some detail would help:

1) Screenshot of "element jumps up"
2) Steps to reproduce the issue
3) Info about any settings or plugins that may be involved—does this happen in Restricted Mode too? or only with certain plugins enabled?
4) What CSS are you currently using to work around the issue?

**Comment by gchegr** [comment] 2022-12-28 09:58
Isaac, hi. No extra steps are require to get this behavior, it just happens when you enable it.All screenshots you have in the plugin’s description — all have the same jump above the baseline.There is no point in testing it further, but here are my screenshots, two of them, one with baselines drawn, the other one is clear. If I enable the Restricted mode to disable community plugins, this would disable the Novel Word Count as well.Anyway, since you asked, I checked it with all third-party plugins disabled, and all CSS-snippets are disabled.As you can see, numbers are moved 2 pixels up. If I enable this snippet, the baselines line up (obviously):.nav-files-container.nav-folder-title::after,.nav-files-container .nav-file-title::after {    font-size: 1em; }And if I make the size smaller instead, the baseline jumps higher, since the scaling is happening from the top corner, and I can’t change it, whatever flexbox property and/or alignment I try.Can you? Egor 25.12.2022, 02:57, "Isaac Lyman" ***@***.***>***@***.*** I've been tweaking a bunch of styles and I'm not able to see the issue you're talking about. Some detail would help:Screenshot of "element jumps up"Steps to reproduce the issueInfo about any settings or plugins that may be involved—does this happen in Restricted Mode too? or only with certain plugins enabled?What CSS are you currently using to work around the issue?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by isaaclyman** [comment] 2023-01-07 17:30
@gchegr It looks like images aren't coming through via email, could you log into GitHub and clean up your message a bit?

**Comment by gchegr** [comment] 2023-01-07 17:38
> @gchegr It looks like images aren't coming through via email, could you log into GitHub and clean up your message a bit?

Done. Do you still need images though?

**Comment by isaaclyman** [comment] 2023-01-07 17:39
Nah. Thanks, that's much more readable. I'll look into it again and see what can be done.

**Comment by isaaclyman** [comment] 2023-01-07 18:00
Fixed in 2.9.2. Turned out to be a pretty simple style fix, and I think it looks better overall, so it's the default now. We'll see if anyone complains.

**Closed by isaaclyman** 2023-01-07 18:00 UTC
Labels: waiting-for-information

**Comment by isaaclyman** [comment] 2023-01-07 18:19
False start. Actual fix in 2.9.3, now that I remembered to compile the CSS. *facepalm*

**Comment by gchegr** [comment] 2023-01-07 18:28
Fixed! What was the fix?

**Comment by isaaclyman** [comment] 2023-01-07 18:29
```css
.nav-files-container .nav-folder-title, .nav-files-container .nav-file-title {
  align-items: baseline;
}
```
