### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by chriszhuliping** [isaaclyman/novel-word-count-obsidian#31] opened 2023-03-04 02:28 UTC
I really love the idea of this plugin. But as a Chinese user, I found that it doesn't support Chinese, could you make it work in Chinese? That would be great!

**Comment by isaaclyman** [comment] 2023-03-04 02:44
Duplicate of #19. If you can tell me how words are counted in Chinese, I will happily implement it.

**Comment by chriszhuliping** [comment] 2023-03-04 02:53
> Duplicate of #19. If you can tell me how words are counted in Chinese, I will happily implement it.

If I write hello in Chinese, it is 你好. So in English, it is one word but in Chines we count it as two words. So each Character in Chinese is a word ( not include the space or something like that). I am not sure if i explain that clearly. Really thank you for your reply!

**Comment by isaaclyman** [comment] 2023-03-04 03:02
So the "character count" option is mostly correct, if it were to ignore punctuation and spacing?

**Comment by chriszhuliping** [comment] 2023-03-04 03:07
> So the "character count" option is mostly correct, if it were to ignore punctuation and spacing?

Exactly! In Chinese, we actually count characters without punctuation and spacing as the “word count” concept

**Comment by isaaclyman** [comment] 2023-03-04 03:09
This is _very_ helpful. I'll see what I can do.

**Comment by chriszhuliping** [comment] 2023-03-04 03:10
That's great!!!

**Comment by isaaclyman** [comment] 2023-03-04 04:38
Version 2.12.0 includes a new setting called "Word count method" for compatibility with CJK characters.

Thanks for the pointers.

**Closed by isaaclyman** 2023-03-04 04:38 UTC
Labels: duplicate, feature request

**Comment by chriszhuliping** [comment] 2023-03-04 05:27
> Version 2.12.0 includes a new setting called "Word count method" for compatibility with CJK characters.
> 
> Thanks for the pointers.

It worked well! Thank you very much!
